"""PR reporter – posts compliance findings as a GitHub PR review comment.

Uses the GitHub REST API via the ``GITHUB_TOKEN`` available in Actions.
"""

from __future__ import annotations

import json
import logging
import os
import urllib.error
import urllib.request
from typing import Any

from .policy_engine import Finding, Severity

logger = logging.getLogger(__name__)

_SEVERITY_EMOJI = {
    Severity.CRITICAL: "🔴",
    Severity.HIGH: "🟠",
    Severity.MEDIUM: "🟡",
    Severity.LOW: "🔵",
    Severity.INFORMATIONAL: "⚪",
}

_SEVERITY_ORDER = [
    Severity.CRITICAL,
    Severity.HIGH,
    Severity.MEDIUM,
    Severity.LOW,
    Severity.INFORMATIONAL,
]


def _github_api(
    method: str,
    url: str,
    token: str,
    payload: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Minimal GitHub API helper using only stdlib urllib."""
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "Content-Type": "application/json",
    }
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req) as resp:  # noqa: S310
            return json.loads(resp.read())
    except urllib.error.HTTPError as exc:
        body = exc.read().decode(errors="replace")
        logger.error("GitHub API %s %s → %s: %s", method, url, exc.code, body)
        raise


def build_report(
    findings: list[Finding],
    *,
    changed_files: list[str],
    pr_title: str = "",
) -> str:
    """Build a markdown compliance report from *findings*."""
    counts: dict[Severity, int] = {s: 0 for s in Severity}
    for f in findings:
        counts[f.severity] += 1

    lines: list[str] = []
    lines.append("## Compliance Check Report")
    lines.append("")

    if pr_title:
        lines.append(f"**PR:** {pr_title}")
        lines.append("")

    # Summary table
    total = len(findings)
    lines.append("### Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    for sev in _SEVERITY_ORDER:
        if counts[sev]:
            lines.append(f"| {_SEVERITY_EMOJI[sev]} {sev.value.capitalize()} | {counts[sev]} |")
    lines.append("")

    if total == 0:
        lines.append("**All checks passed.** No policy violations found.")
        lines.append("")
    else:
        lines.append(
            f"**{total} violation(s) found** across {len(changed_files)} checked file(s)."
        )
        lines.append("")
        lines.append("### Findings")
        lines.append("")

        # Group by severity
        for sev in _SEVERITY_ORDER:
            sev_findings = [f for f in findings if f.severity == sev]
            if not sev_findings:
                continue
            lines.append(
                f"#### {_SEVERITY_EMOJI[sev]} {sev.value.capitalize()} ({len(sev_findings)})"
            )
            lines.append("")
            lines.append("| Rule | Resource | File | Description |")
            lines.append("|------|----------|------|-------------|")
            for finding in sev_findings:
                desc = finding.description.replace("\n", " ").replace("|", "\\|")
                fname = finding.file.split("/")[-1] if finding.file else ""
                lines.append(
                    f"| `{finding.rule_id}` | "
                    f"`{finding.resource_type}.{finding.resource_name}` | "
                    f"`{fname}` | "
                    f"{desc} |"
                )
            lines.append("")

        # Recommendations
        lines.append("### Recommendations")
        lines.append("")
        seen_rules: set[str] = set()
        for sev in _SEVERITY_ORDER:
            for finding in findings:
                if finding.severity == sev and finding.rule_id not in seen_rules:
                    seen_rules.add(finding.rule_id)
                    lines.append(
                        f"- **`{finding.rule_id}`** ({sev.value}): {finding.recommendation}"
                    )
        lines.append("")

    lines.append(
        "<sub>Generated by the Compliance Check Agent. "
        "Review each finding and apply the recommended remediation.</sub>"
    )
    return "\n".join(lines)


class PRReporter:
    """Posts compliance findings as a comment on a GitHub Pull Request.

    Parameters
    ----------
    token:
        GitHub token with ``pull-requests: write`` permission.
    repo:
        ``owner/repo`` string.
    pr_number:
        Pull request number.
    api_base:
        GitHub API base URL (defaults to ``https://api.github.com``).
    """

    def __init__(
        self,
        token: str,
        repo: str,
        pr_number: int,
        api_base: str = "https://api.github.com",
    ) -> None:
        self._token = token
        self._repo = repo
        self._pr_number = pr_number
        self._api_base = api_base.rstrip("/")

    @classmethod
    def from_env(cls) -> PRReporter:
        """Build a PRReporter from standard GitHub Actions environment variables."""
        token = os.environ.get("GITHUB_TOKEN", "")
        repo = os.environ.get("GITHUB_REPOSITORY", "")
        pr_number = int(os.environ.get("PR_NUMBER", "0"))
        api_base = os.environ.get("GITHUB_API_URL", "https://api.github.com")
        if not token or not repo or not pr_number:
            raise OSError(
                "Missing required environment variables: GITHUB_TOKEN, "
                "GITHUB_REPOSITORY, PR_NUMBER"
            )
        return cls(token=token, repo=repo, pr_number=pr_number, api_base=api_base)

    def post_comment(self, body: str) -> None:
        """Post *body* as a new PR comment, replacing any previous compliance comment."""
        url = f"{self._api_base}/repos/{self._repo}/issues/{self._pr_number}/comments"

        # Delete existing compliance bot comments to avoid clutter
        try:
            existing = _github_api("GET", url, self._token)
            if isinstance(existing, list):
                for comment in existing:
                    if isinstance(comment, dict) and "## Compliance Check Report" in comment.get(
                        "body", ""
                    ):
                        del_url = (
                            f"{self._api_base}/repos/{self._repo}/issues/comments/{comment['id']}"
                        )
                        _github_api("DELETE", del_url, self._token)
                        logger.debug("Deleted previous compliance comment %s", comment["id"])
        except Exception as exc:
            logger.warning("Could not clean up previous comments: %s", exc)

        _github_api("POST", url, self._token, {"body": body})
        logger.info("Posted compliance report to PR #%s", self._pr_number)
