name: "CI/CD"

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  call-vending-workflow:
    # Point this to your Meta-Repo's reusable workflow
    uses: Egoorbis/gh-project-vending-machine/actions/reusable-deploy.yml@main
    with:
      env: "production"
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
